### ISSUE TITLE
Agree on an agenda!

### ISSUE THREAD

**Issue by pjozsef** [gmiklos-inst/codelabs#2]
Let's discuss what sessions we would like to have during the week.
Feel free to comment with suggestions and/or topics that you would like present.

**Comment by pjozsef** [comment]
I think it would be great to have short introductory presentations for the following:
Kotlin, Typescript, React.
I'd be glad to do a short Kotlin intro presentation.

We could also have a coding dojo kind of thing, to have some pair coding and TDD in Kotlin before the workshop.

Having a selenium session would be great as well. Maybe integrated into the TODO workshop app?

**Comment by devill** [comment]
There is an existing document with my plans for the week. 
https://docs.google.com/document/d/1ixdCtHYkc-GJa10vCvt_cQpzOm8v7w0ikJYvGoihPyw/edit?usp=sharing

**Comment by devill** [comment]
What I will need though is approximate times for each of the presentations

**Comment by pjozsef** [comment]
Agenda got created, thus closing this issue.
